import React, {useState, useEffect, useRef} from 'react';

function Mickey() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [context, setContext] = useState<CanvasRenderingContext2D | null>(null);

  useEffect(() => {

    if(canvasRef.current){
      const renderCtx = canvasRef.current.getContext("2d");

      if(renderCtx){
        setContext(renderCtx)
      }

      if(context) {
        //background
//sky
context.beginPath();
context.rect(0, 0, 2000, 1000);
context.fillStyle = "midnightBlue";
context.fill();
context.closePath();
//grass
context.beginPath();
context.rect(0, 500, 2000, 500);
context.fillStyle = "seaGreen";
context.fill();
context.closePath();
//weather
//stars
context.beginPath();
context.arc(40, 30, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1850, 30, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(30, 130, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1840, 130, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(150, 50, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1720, 50, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(850, 130, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1150, 130, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(750, 30, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(950, 30, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(370, 60, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1270, 60, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(550, 80, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(420, 145, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(200, 115, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(300, 190, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(90, 225, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(190, 287, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(300, 367, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(60, 407, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(900, 457, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(810, 425, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1855, 320, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1755, 380, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(855, 320, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1760, 230, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(760, 230, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1560, 230, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(560, 230, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(410, 300, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1410, 300, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(510, 450, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1310, 450, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(610, 370, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1210, 370, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(680, 150, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1280, 200, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(1480, 120, 1, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();

//
//house
context.beginPath();
context.rect(720, 260, 400, 350);
context.fillStyle = "lightSalmon";
context.fill();
context.closePath();
//
//smoke
context.beginPath();
context.arc(1043, 150, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1035, 135, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1045, 125, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1030, 115, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1040, 100, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1035, 80, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1025, 60, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1035, 40, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1030, 20, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
context.beginPath();
context.arc(1020, 10, 15, 0, Math.PI * 2, false);
context.fillStyle = "grey";
context.fill();
context.closePath();
//
//house chimmney
context.beginPath();
context.rect(1025, 160, 35, 70);
context.fillStyle = "black";
context.fill();
context.closePath();
//
//houseRoof
context.beginPath();
context.moveTo(1130, 265);
context.lineTo(710, 265);
context.lineTo(915, 140);
context.fillStyle = "darkRed";
context.fill();
context.closePath();
//

//
//door
context.beginPath();
context.rect(780, 470, 80, 140);
context.fillStyle = "darkGoldenRod";
context.fill();
context.closePath();
//
//doorWindow
context.beginPath();
context.ellipse(820, 500, 15, 25, Math.PI / 2, 0, Math.PI * 2);
context.fillStyle = "lightYellow";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//door window pattern
context.beginPath();
context.moveTo(845, 500);
context.lineTo(795, 500);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(820, 485);
context.lineTo(820, 515);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();

//wreath
context.beginPath();
context.arc(820, 525, 8, 0, Math.PI * 2, true);
context.lineWidth = 4;
context.strokeStyle = "green";
context.stroke();
context.closePath();
context.beginPath();
context.arc(820, 535, 3, 0, Math.PI * 2, true);
context.fillStyle = "red";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(820, 535);
context.lineTo(815, 540);
context.moveTo(820, 535);
context.lineTo(825, 540);
context.lineWidth = 3;
context.strokeStyle = "red";
context.stroke();
context.closePath();

//doorknob
context.beginPath();
context.arc(795, 545, 5, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();

//window1
context.beginPath();
context.rect(780, 310, 80, 80);
context.fillStyle = "lightYellow";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//curtain for window one
context.beginPath();
context.rect(782, 311, 76, 75);
context.fillStyle = "purple";
context.fill();
context.closePath();
//
//window one pattern
context.beginPath();
context.moveTo(780, 352);
context.lineTo(860, 352);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(820, 310);
context.lineTo(820, 390);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//underWindow
context.beginPath();
context.rect(775, 390, 90, 10);
context.fillStyle = "grey";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//
//snow window 1
context.beginPath();
context.arc(780, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(785, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(790, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(795, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(800, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(805, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(810, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(815, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(820, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(825, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(830, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(835, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(840, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(845, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(850, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(855, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(860, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
//
//
//window2
context.beginPath();
context.rect(960, 310, 80, 80);
context.fillStyle = "lightYellow";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//curtain for window 2
context.beginPath();
context.rect(962, 311, 76, 75);
context.fillStyle = "purple";
context.fill();
context.closePath();
//
//window 2 pattern
context.beginPath();
context.moveTo(960, 352);
context.lineTo(1040, 352);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1000, 310);
context.lineTo(1000, 390);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//underWindow2
context.beginPath();
context.rect(955, 390, 90, 10);
context.fillStyle = "grey";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//
//snow window 2
context.beginPath();
context.arc(960, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(965, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(970, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(975, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(980, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(985, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(990, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(995, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1000, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1005, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1010, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1015, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1020, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1025, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1030, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1035, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1040, 387, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
//
//
//window3
context.beginPath();
context.rect(960, 470, 80, 80);
context.fillStyle = "lightYellow";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//curtain for window3
context.beginPath();
context.rect(962, 471, 76, 75);
context.fillStyle = "purple";
context.fill();
context.closePath();
//
//window 3 pattern
context.beginPath();
context.moveTo(960, 510);
context.lineTo(1040, 510);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1000, 550);
context.lineTo(1000, 470);
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//underWindow3
context.beginPath();
context.rect(955, 550, 90, 10);
context.fillStyle = "grey";
context.fill();
context.lineWidth = 3;
context.strokeStyle = "black";
context.stroke();
context.closePath();
//
//snow window 3
context.beginPath();
context.arc(960, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(965, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(970, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(975, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(980, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(985, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(990, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(995, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1000, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1005, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1010, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1015, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1020, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1025, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1030, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1035, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1040, 548, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();

//tree
//trunk
context.beginPath();
context.rect(205, 670, 80, 260);
context.fillStyle = "saddleBrown";
context.fill();
context.closePath();

//Xmas leaves

context.beginPath();
context.moveTo(425, 765);
context.lineTo(80, 765);
context.lineTo(245, 620);
context.fillStyle = "darkGreen";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(395, 680);
context.lineTo(245, 535);
context.lineTo(115, 680);
context.fillStyle = "darkGreen";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(345, 600);
context.lineTo(245, 485);
context.lineTo(145, 600);
context.fillStyle = "darkGreen";
context.fill();
context.closePath();

//XmasStar

context.beginPath();
context.moveTo(245, 480);
context.lineTo(285, 510);
context.lineTo(260, 460);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(245, 440);
context.lineTo(245, 480);
context.lineTo(295, 440);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(190, 440);
context.lineTo(245, 480);
context.lineTo(295, 440);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(240, 400);
context.lineTo(230, 440);
context.lineTo(255, 440);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.moveTo(245, 480);
context.lineTo(210, 510);
context.lineTo(225, 460);
context.fillStyle = "yellow";
context.fill();
context.closePath();

//tinsel

context.beginPath();
context.moveTo(300, 550);
context.bezierCurveTo(238, 600, 230, 590, 185, 600);
context.lineWidth = 5;
context.strokeStyle = "silver";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(330, 615);
context.bezierCurveTo(225, 680, 200, 660, 125, 672);
context.lineWidth = 5;
context.strokeStyle = "silver";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(340, 695);
context.bezierCurveTo(250, 750, 245, 735, 98, 750);
context.lineWidth = 5;
context.strokeStyle = "silver";
context.stroke();
context.closePath();

//baubles
context.beginPath();
context.arc(420, 768, 5, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(85, 768, 5, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(393, 686, 5, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(118, 686, 5, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(343, 605, 5, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(150, 605, 5, 0, Math.PI * 2, true);
context.fillStyle = "yellow";
context.fill();
context.closePath();
context.beginPath();
context.arc(250, 525, 5, 0, Math.PI * 2, true);
context.fillStyle = "red";
context.fill();
context.closePath();
context.beginPath();
context.arc(210, 565, 5, 0, Math.PI * 2, true);
context.fillStyle = "orange";
context.fill();
context.closePath();
context.beginPath();
context.arc(265, 605, 5, 0, Math.PI * 2, true);
context.fillStyle = "cyan";
context.fill();
context.closePath();
context.beginPath();
context.arc(200, 630, 5, 0, Math.PI * 2, true);
context.fillStyle = "purple";
context.fill();
context.closePath();
context.beginPath();
context.arc(330, 655, 5, 0, Math.PI * 2, true);
context.fillStyle = "silver";
context.fill();
context.closePath();
context.beginPath();
context.arc(285, 675, 5, 0, Math.PI * 2, true);
context.fillStyle = "orange";
context.fill();
context.closePath();
context.beginPath();
context.arc(205, 690, 5, 0, Math.PI * 2, true);
context.fillStyle = "red";
context.fill();
context.closePath();
context.beginPath();
context.arc(305, 750, 5, 0, Math.PI * 2, true);
context.fillStyle = "purple";
context.fill();
context.closePath();
context.beginPath();
context.arc(345, 725, 5, 0, Math.PI * 2, true);
context.fillStyle = "orange";
context.fill();
context.closePath();
context.beginPath();
context.arc(150, 725, 5, 0, Math.PI * 2, true);
context.fillStyle = "cyan";
context.fill();
context.closePath();
context.beginPath();
context.arc(240, 710, 5, 0, Math.PI * 2, true);
context.fillStyle = "silver";
context.fill();
context.closePath();

//roof snow
context.beginPath();
context.arc(715, 260, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(720, 256, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(725, 252, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(730, 248, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(735, 245, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(740, 241, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(745, 238, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(750, 235, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(755, 232, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(760, 229, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(765, 226, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(770, 223, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(775, 220, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(780, 217, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(785, 214, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(790, 211, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(795, 208, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(800, 205, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(805, 202, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(810, 199, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(815, 196, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(820, 193, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(825, 190, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(830, 187, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(835, 184, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(840, 181, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(845, 178, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(850, 175, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(855, 172, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(860, 169, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(865, 166, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(870, 163, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(875, 160, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(880, 157, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(885, 154, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(890, 151, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(895, 148, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(900, 145, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(905, 142, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(910, 139, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
//
//

context.beginPath();
context.arc(915, 139, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(920, 142, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(925, 145, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(930, 148, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(935, 151, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(940, 154, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(945, 157, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(950, 160, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(955, 163, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(960, 166, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(965, 169, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(970, 172, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(975, 175, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(980, 178, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(985, 181, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(990, 184, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(995, 187, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1000, 190, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1005, 193, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1010, 196, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1015, 199, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1020, 202, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1025, 205, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1030, 208, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1035, 211, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1040, 214, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1045, 217, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1050, 220, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1055, 223, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1060, 226, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1065, 229, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1070, 232, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1075, 235, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1080, 238, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1085, 241, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1090, 244, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1095, 247, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1100, 250, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1105, 253, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1110, 256, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1115, 259, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.beginPath();
context.arc(1120, 262, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1125, 265, 5, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();

//
//word
context.beginPath();
context.font = "60px Comic Sans MS";
context.fillStyle = "white";
context.fillText("Thank You", 70, 170);
context.closePath();
context.beginPath();
context.font = "55px Comic Sans MS";
context.fillStyle = "white";
context.fillText("School Of Code", 180, 240);
context.closePath();
context.beginPath();
context.font = "55px Comic Sans MS";
context.fillStyle = "white";
context.fillText("Happy", 1270, 170);
context.closePath();
context.beginPath();
context.font = "55px Comic Sans MS";
context.fillStyle = "white";
context.fillText("Holidays", 1370, 240);
context.closePath();
context.beginPath();
context.font = "55px Comic Sans MS";
context.fillStyle = "white";
context.fillText("Everyone", 770, 730);
context.closePath();
context.beginPath();
context.font = "55px Comic Sans MS";
context.fillStyle = "white";
context.fillText("Xxx", 840, 800);
context.closePath();

//snowmanArms
context.beginPath();
context.moveTo(1600, 585);
context.lineTo(1660, 560);
context.strokeStyle = "saddleBrown";
context.lineWidth = 7;
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1635, 570);
context.lineTo(1645, 540);
context.strokeStyle = "saddleBrown";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1635, 570);
context.lineTo(1660, 585);
context.strokeStyle = "saddleBrown";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1485, 580);
context.lineTo(1430, 555);
context.strokeStyle = "saddleBrown";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1460, 570);
context.lineTo(1450, 535);
context.strokeStyle = "saddleBrown";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1465, 570);
context.lineTo(1430, 580);
context.strokeStyle = "saddleBrown";
context.stroke();
context.closePath();

//
//snowman
//body

context.beginPath();
context.arc(1540, 700, 85, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1540, 600, 65, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();
context.beginPath();
context.arc(1540, 520, 55, 0, Math.PI * 2, true);
context.fillStyle = "white";
context.fill();
context.closePath();

//snowmanHat
context.beginPath();
context.rect(1490, 455, 95, 15);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.rect(1510, 410, 55, 60);
context.fillStyle = "black";
context.fill();
context.closePath();

//SnowmanEyes
context.beginPath();
context.arc(1525, 495, 6, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1553, 495, 6, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
//snowmanNose
context.beginPath();
context.moveTo(1540, 530);
context.lineTo(1550, 508);
context.lineTo(1530, 508);
context.fillStyle = "orange";
context.fill();
context.closePath();
//snowmanMouth
context.beginPath();
context.arc(1515, 520, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1519, 528, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1527, 534, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1540, 536, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1552, 534, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1560, 528, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1564, 520, 4, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();

//snowmanButtons
context.beginPath();
context.arc(1540, 590, 7, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1540, 640, 7, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();
context.beginPath();
context.arc(1540, 700, 7, 0, Math.PI * 2, true);
context.fillStyle = "black";
context.fill();
context.closePath();

//snowmanScarf
context.beginPath();
context.moveTo(1590, 555);
context.bezierCurveTo(1560, 565, 1510, 565, 1490, 555);
context.lineWidth = 9;
context.strokeStyle = "purple";
context.stroke();
context.closePath();
context.beginPath();
context.moveTo(1567, 560);
context.bezierCurveTo(1560, 560, 1575, 560, 1580, 620);
context.lineWidth = 9;
context.strokeStyle = "purple";
context.stroke();
context.closePath();

      }
      
    }
  }, [context]);

  return (
    <div
      style={{
        textAlign: 'center',
      }}>
        <p>Xmas House SoC Message</p>
      <canvas
        id="canvas"
        ref={canvasRef}
        width={window.innerWidth}
        height={window.innerHeight}
        style={{
          border: '2px solid #000',
          marginTop: 10,
          marginLeft: 10,
          marginRight: 10,
          marginBottom: 10,
        }}
      ></canvas>
    </div>
  );
}

export default Mickey;